### ISSUE TITLE
When the translation is not turned on, each English paragraph will appear repeatedly.

### ISSUE THREAD

**Issue by gaoyanliang** [Roiocam/chrome-dual-translate-script#2]
After adding this script, when I was reading the English document, the following situation occurred without translation enabled

![image](https://user-images.githubusercontent.com/33021341/149457934-2d6a7c86-bf28-493e-8b12-e747a614d641.png)

![image](https://user-images.githubusercontent.com/33021341/149458000-98000502-22a0-4e4e-8538-6d16006165f1.png)

Is there something wrong with my usage?

**Comment by Roiocam** [comment]
it's an issue, i'm try to fix on #3 . it 's not pretty, but work as well for me

**Comment by Roiocam** [comment]
i will merge this feature to master branch

**Comment by gaoyanliang** [comment]
ok, I will try the latest script
